export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const AUTH_SET_LOADING = "AUTH_SET_LOADING";
export const AUTH_NOTIFICATION = "AUTH_NOTIFICATION";
export const CHECK_MEMBERSHIP="CHECK_MEMBERSHIP";
export const GET_SUBCTION_DETAIL="GET_SUBCTION_DETAIL";
export const CONFIRM_CANCEL_MEMBERSHIP = "CONFIRM_CANCEL_MEMBERSHIP";
export const QUESTION_ANS = "QUESTION_ANS";
